package com.magicalhippie.aprende.domain.srs

import kotlin.math.E
import kotlin.math.max
import kotlin.math.min
import kotlin.math.pow
import kotlin.math.round

/**
 * FSRS-6 grade. Values match the canonical open-spaced-repetition `Rating` enum (1..4):
 * Again=1, Hard=2, Good=3, Easy=4. The app derives these from exercise outcomes (it never
 * asks the learner to self-rate) — see [ScheduleReviewUseCase] and SPEC §6.4.
 */
enum class FsrsRating(val value: Int) {
    AGAIN(1),
    HARD(2),
    GOOD(3),
    EASY(4),
}

/**
 * Per-item memory state (SPEC §6.1). [difficulty]/[stability] are the FSRS D/S; timestamps
 * are epoch-millis. "Is this item due now?" is the pure comparison `now >= dueAtMillis`
 * (SPEC §6.5 — lazy, no background job).
 */
data class SrsItemState(
    val difficulty: Double,
    val stability: Double,
    val lastReviewMillis: Long,
    val dueAtMillis: Long,
)

/**
 * Pure FSRS-6 scheduler — the long-term (day-scale) variant with NO learning/relearning
 * steps, equivalent to the canonical FSRS-6 scheduler configured with empty steps and
 * fuzzing off. Stateless and fully deterministic (all inputs explicit), so it is verified
 * on the JVM against reference vectors generated by the canonical library (see FsrsTest).
 *
 * SPEC D1: there is no `SrsScheduler` interface — this class is the single engine and
 * [ScheduleReviewUseCase] is the seam. SPEC §6.2 documents every formula below.
 */
class Fsrs(
    val parameters: DoubleArray = DEFAULT_PARAMETERS,
    val desiredRetention: Double = 0.9,
    val maximumIntervalDays: Int = 36_500,
) {
    init {
        require(parameters.size == 21) { "FSRS-6 requires 21 parameters, got ${parameters.size}" }
        require(parameters[20] > 0.0) { "w20 (decay) must be > 0, was ${parameters[20]}" }
        require(desiredRetention > 0.0 && desiredRetention < 1.0) {
            "desiredRetention must be in (0,1), was $desiredRetention"
        }
    }

    private val decay: Double = -parameters[20]
    private val factor: Double = 0.9.pow(1.0 / decay) - 1.0

    /** Predicted recall probability after [elapsedDays] since last review at the given [stability]. */
    fun retrievability(elapsedDays: Long, stability: Double): Double {
        val t = max(0L, elapsedDays).toDouble()
        return (1.0 + factor * t / stability).pow(decay)
    }

    /** Whole-day interval to the next review for [stability] at [desiredRetention]; clamped to [1, max]. */
    fun nextIntervalDays(stability: Double): Int {
        val raw = (stability / factor) * (desiredRetention.pow(1.0 / decay) - 1.0)
        return min(max(round(raw).toInt(), 1), maximumIntervalDays)
    }

    /** First-ever review of a brand-new item. */
    fun firstReview(rating: FsrsRating, nowMillis: Long): SrsItemState {
        val stability = initialStability(rating)
        val difficulty = initialDifficulty(rating, clamp = true)
        return stateFrom(difficulty, stability, nowMillis)
    }

    /**
     * Subsequent review of an existing item. Matches the canonical order: the new stability is
     * computed from the OLD difficulty, then difficulty is updated.
     */
    fun review(prev: SrsItemState, rating: FsrsRating, nowMillis: Long): SrsItemState {
        val elapsedDays = floorDayDelta(prev.lastReviewMillis, nowMillis)
        val r = retrievability(elapsedDays, prev.stability)
        val newStability = nextStability(prev.difficulty, prev.stability, r, rating)
        val newDifficulty = nextDifficulty(prev.difficulty, rating)
        return stateFrom(newDifficulty, newStability, nowMillis)
    }

    private fun stateFrom(difficulty: Double, stability: Double, nowMillis: Long): SrsItemState =
        SrsItemState(
            difficulty = difficulty,
            stability = stability,
            lastReviewMillis = nowMillis,
            dueAtMillis = nowMillis + nextIntervalDays(stability).toLong() * DAY_MILLIS,
        )

    private fun clampStability(s: Double): Double = max(s, STABILITY_MIN)

    private fun clampDifficulty(d: Double): Double = min(max(d, MIN_DIFFICULTY), MAX_DIFFICULTY)

    private fun initialStability(rating: FsrsRating): Double =
        clampStability(parameters[rating.value - 1])

    private fun initialDifficulty(rating: FsrsRating, clamp: Boolean): Double {
        val d = parameters[4] - E.pow(parameters[5] * (rating.value - 1)) + 1.0
        return if (clamp) clampDifficulty(d) else d
    }

    private fun nextDifficulty(difficulty: Double, rating: FsrsRating): Double {
        // Target of mean reversion is the UNCLAMPED initial difficulty for Easy.
        val arg1 = initialDifficulty(FsrsRating.EASY, clamp = false)
        val deltaDifficulty = -(parameters[6] * (rating.value - 3))
        val damped = difficulty + (10.0 - difficulty) * deltaDifficulty / 9.0 // linear damping
        val reverted = parameters[7] * arg1 + (1.0 - parameters[7]) * damped
        return clampDifficulty(reverted)
    }

    private fun nextStability(difficulty: Double, stability: Double, r: Double, rating: FsrsRating): Double {
        val next = if (rating == FsrsRating.AGAIN) {
            nextForgetStability(difficulty, stability, r)
        } else {
            nextRecallStability(difficulty, stability, r, rating)
        }
        return clampStability(next)
    }

    private fun nextRecallStability(difficulty: Double, stability: Double, r: Double, rating: FsrsRating): Double {
        val hardPenalty = if (rating == FsrsRating.HARD) parameters[15] else 1.0
        val easyBonus = if (rating == FsrsRating.EASY) parameters[16] else 1.0
        return stability * (
            1.0 + E.pow(parameters[8]) *
                (11.0 - difficulty) *
                stability.pow(-parameters[9]) *
                (E.pow((1.0 - r) * parameters[10]) - 1.0) *
                hardPenalty *
                easyBonus
            )
    }

    private fun nextForgetStability(difficulty: Double, stability: Double, r: Double): Double {
        val longTerm = parameters[11] *
            difficulty.pow(-parameters[12]) *
            ((stability + 1.0).pow(parameters[13]) - 1.0) *
            E.pow((1.0 - r) * parameters[14])
        val shortTerm = stability / E.pow(parameters[17] * parameters[18])
        return min(longTerm, shortTerm)
    }

    companion object {
        /** Canonical FSRS-6 default weights (w0..w20). */
        val DEFAULT_PARAMETERS: DoubleArray = doubleArrayOf(
            0.212, 1.2931, 2.3065, 8.2956, 6.4133, 0.8334, 3.0194, 0.001, 1.8722, 0.1666,
            0.796, 1.4835, 0.0614, 0.2629, 1.6483, 0.6014, 1.8729, 0.5425, 0.0912, 0.0658, 0.1542,
        )

        const val STABILITY_MIN: Double = 0.001
        const val MIN_DIFFICULTY: Double = 1.0
        const val MAX_DIFFICULTY: Double = 10.0
        const val DAY_MILLIS: Long = 86_400_000L

        /** Whole days between two epoch-millis instants (floor, never negative) — matches the canonical `.days`. */
        fun floorDayDelta(fromMillis: Long, toMillis: Long): Long = max(0L, (toMillis - fromMillis) / DAY_MILLIS)
    }
}
