package com.magicalhippie.aprende.domain.srs

import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test

/**
 * FSRS-6 correctness against REFERENCE VECTORS generated by the canonical
 * open-spaced-repetition `fsrs` Python library (FSRS-6, default weights, desiredRetention=0.9,
 * empty learning/relearning steps, fuzzing off) — the same configuration this engine models.
 * This is the AC5 oracle: the numbers below are the library's output, not self-computed.
 *
 * Tolerance 1e-6 on D/S/R (double `pow` rounding); intervals are exact whole days.
 */
class FsrsTest {

    private val fsrs = Fsrs()
    private val tol = 1e-6
    private val t0 = 1_700_000_000_000L // arbitrary epoch millis

    private fun assertClose(expected: Double, actual: Double, what: String) {
        assertEquals(what, expected, actual, tol)
    }

    private fun intervalDays(state: SrsItemState, reviewedAtMillis: Long): Long =
        (state.dueAtMillis - reviewedAtMillis) / Fsrs.DAY_MILLIS

    @Test
    fun `initial state matches reference for each rating`() {
        data class Init(val rating: FsrsRating, val s: Double, val d: Double, val interval: Long)
        val refs = listOf(
            Init(FsrsRating.AGAIN, 0.212, 6.4133, 1),
            Init(FsrsRating.HARD, 1.2931, 5.112170705601056, 1),
            Init(FsrsRating.GOOD, 2.3065, 2.118103970459016, 2),
            Init(FsrsRating.EASY, 8.2956, 1.0, 8),
        )
        for (r in refs) {
            val s = fsrs.firstReview(r.rating, t0)
            assertClose(r.s, s.stability, "${r.rating} initial stability")
            assertClose(r.d, s.difficulty, "${r.rating} initial difficulty")
            assertEquals("${r.rating} initial interval", r.interval, intervalDays(s, t0))
        }
    }

    @Test
    fun `three successful Good reviews match reference stability growth`() {
        // Reference: Good -> Good(+2d) -> Good(+11d)
        var reviewedAt = t0
        var state = fsrs.firstReview(FsrsRating.GOOD, reviewedAt)
        assertClose(2.3065, state.stability, "step0 S")
        assertEquals(2L, intervalDays(state, reviewedAt))

        reviewedAt = state.dueAtMillis
        state = fsrs.review(state, FsrsRating.GOOD, reviewedAt)
        assertClose(10.964332335820698, state.stability, "step1 S")
        assertClose(2.111214235785395, state.difficulty, "step1 D")
        assertEquals(11L, intervalDays(state, reviewedAt))

        reviewedAt = state.dueAtMillis
        state = fsrs.review(state, FsrsRating.GOOD, reviewedAt)
        assertClose(46.28021728755693, state.stability, "step2 S")
        assertClose(2.1043313908464483, state.difficulty, "step2 D")
        assertEquals(46L, intervalDays(state, reviewedAt))
    }

    @Test
    fun `a lapse (Again) drops stability and raises difficulty per reference`() {
        var reviewedAt = t0
        var state = fsrs.firstReview(FsrsRating.GOOD, reviewedAt)
        reviewedAt = state.dueAtMillis
        state = fsrs.review(state, FsrsRating.AGAIN, reviewedAt)
        assertClose(0.6075801062519337, state.stability, "post-lapse S")
        assertClose(7.394502741279718, state.difficulty, "post-lapse D")
        assertEquals(1L, intervalDays(state, reviewedAt))
    }

    @Test
    fun `Hard then Good then Easy matches reference`() {
        var reviewedAt = t0
        var state = fsrs.firstReview(FsrsRating.HARD, reviewedAt)
        assertClose(1.2931, state.stability, "hard S")
        assertClose(5.112170705601056, state.difficulty, "hard D")
        assertEquals(1L, intervalDays(state, reviewedAt))

        reviewedAt = state.dueAtMillis
        state = fsrs.review(state, FsrsRating.GOOD, reviewedAt)
        assertClose(4.546029441066125, state.stability, "good S")
        assertClose(5.102286904192293, state.difficulty, "good D")
        assertEquals(5L, intervalDays(state, reviewedAt))

        reviewedAt = state.dueAtMillis
        state = fsrs.review(state, FsrsRating.EASY, reviewedAt)
        assertClose(27.030634318325546, state.stability, "easy S")
        assertClose(3.4509277903004603, state.difficulty, "easy D")
        assertEquals(27L, intervalDays(state, reviewedAt))
    }

    @Test
    fun `retrievability matches reference for stability 2_3065`() {
        val s = 2.3065
        assertClose(1.0, fsrs.retrievability(0, s), "R(0)")
        assertClose(0.9468474993825461, fsrs.retrievability(1, s), "R(1)")
        assertClose(0.9094932559773545, fsrs.retrievability(2, s), "R(2)")
        assertClose(0.8809479557659419, fsrs.retrievability(3, s), "R(3)")
        assertClose(0.8388614268145294, fsrs.retrievability(5, s), "R(5)")
    }

    @Test
    fun `interval at default retention equals stability (rounded) — the I(0_9,S)=S identity`() {
        // I(0.9, S) == S exactly (algebraic identity; catches any factor/decay sign error),
        // then rounded to whole days.
        assertEquals(1, fsrs.nextIntervalDays(1.0))
        assertEquals(2, fsrs.nextIntervalDays(2.3065))
        assertEquals(5, fsrs.nextIntervalDays(5.0))
        assertEquals(10, fsrs.nextIntervalDays(10.0))
        assertEquals(50, fsrs.nextIntervalDays(50.0))
    }

    @Test
    fun `correct review schedules strictly later than a wrong review from the same state (AC5)`() {
        val reviewedAt = t0
        val prev = fsrs.firstReview(FsrsRating.GOOD, reviewedAt)
        val later = prev.dueAtMillis

        val afterGood = fsrs.review(prev, FsrsRating.GOOD, later)
        val afterAgain = fsrs.review(prev, FsrsRating.AGAIN, later)

        assertTrue(
            "correct (Good) must schedule later than wrong (Again)",
            afterGood.dueAtMillis > afterAgain.dueAtMillis,
        )
        assertTrue("Good must not reduce stability", afterGood.stability > prev.stability)
        assertTrue("Again must reduce stability", afterAgain.stability < prev.stability)
    }

    @Test
    fun `stability and difficulty stay within valid bounds`() {
        // Difficulty clamped to [1,10]; stability never below the floor.
        val easy = fsrs.firstReview(FsrsRating.EASY, t0)
        assertTrue(easy.difficulty in Fsrs.MIN_DIFFICULTY..Fsrs.MAX_DIFFICULTY)
        assertTrue(easy.stability >= Fsrs.STABILITY_MIN)
        val again = fsrs.firstReview(FsrsRating.AGAIN, t0)
        assertTrue(again.difficulty in Fsrs.MIN_DIFFICULTY..Fsrs.MAX_DIFFICULTY)
    }

    @Test
    fun `requires exactly 21 parameters`() {
        try {
            Fsrs(parameters = DoubleArray(17))
            throw AssertionError("expected IllegalArgumentException for wrong parameter count")
        } catch (e: IllegalArgumentException) {
            // expected
        }
    }
}
